import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import ListToken from "../components/list";


export default function Home({ data}) {

  
  

  return (
    <div className={styles.container}>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <main className={styles.main}>
        <button style={{ border: "1px solid", borderRadius: 8, padding: 8 }}>
          CREATE NEW ERC20
        </button>

        <ListToken />

        
      </main>
    </div>
  );
}


